### ISSUE TITLE
Spanish: shows erroneous text

### ISSUE THREAD

**Issue by sirgabouy** [LayoutXML/Twelveish#12]
hi, I think it's a Spanish translation problem.
When the minute hand is between 10 and 14, it shows <almost the "HH" and ten> and should show <almost the "HH" and quarter>.
for example in the attached photo are 20:12 and the text should be: casi las ocho y cuarto

![screen](https://user-images.githubusercontent.com/49125742/55292005-da6bd300-53bb-11e9-8637-91e1690f5b31.png)

**Comment by LayoutXML** [comment]
Hi, thank you. I will fix it in a few days.

**Comment by LayoutXML** [comment]
Changed the translation. Next version of Twelveish will have this translation fixed.
