### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by elawhatson** [LayoutXML/Twelveish#2]
hello, I would like to offer you a new logo for your project.
What do you think? im a designer glad to contribute open source projects, so if you agree I can start with some ideas, we can work together until we found what fits perfect with this project.

**Comment by LayoutXML** [comment]
Hi, sure, this would be wonderful. The only problem I can think of is that now I am using 3 logos - one on the Google Play store (which is essentially a screenshot of the watch face), one that is visible in the watch face selection menu (another screenshot but this time without a frame) and one in the backend - in the android settings (this is the actual icon that is defined in the application).

**Ideally** first two would actually show how the watch face looks like - this is what users would want to see in the Google Play store and in the watch faces library on their devices.

Anyway, I want to see what you think about this.

**Comment by LayoutXML** [comment]
Hi again,
I have just made some layout changes - added two more complications on the sides so if your logo idea involves preview of how the watch face looks, it might be better if you could add them as well. This is how it looks like now: https://imgur.com/a/g15FOnj.

**Comment by elawhatson** [comment]
don't worry about it sir there are no compromises. I want to show you some ideas I have for your project and you can tell me how it looks like and if it fits.

I saw the logos and are cool, but personally, the minimalist style is better for showing what your app does.
ill be sending sketches, stay tuned sir.💪

**Comment by LayoutXML** [comment]
Hey, how is it going?

**Comment by elawhatson** [comment]
![test](https://user-images.githubusercontent.com/43912079/47122960-0436a080-d247-11e8-9e22-9da986bfc5d2.png)
sorry for the delayed answer. I was thinking of conserve the logo you have in Google play because it explains perfectly your project.
but I made a more minimalist look, for making this easier for the people to see understand what is the logo saying or what he does.✌️
what do you think?

**Comment by LayoutXML** [comment]
This is awesome!

**Comment by LayoutXML** [comment]
What are the restrictions and conditions for using your icons? What name do you want to be contributed by in the app description and in the app itself?

**Comment by elawhatson** [comment]
this is totally free and there's no any condition to use my logo when I  contributed to the project.
would be perfect if you put my name in the project as a contributor, but as I said only if you want to.
By the way in what folder of the project you want to storage de logos? 
I´ll fix the alignment of the watch a bit. then I'll make the Pull Request😃

**Comment by LayoutXML** [comment]
If you're going to make different sizes then put it in the drawable folders in
app > source > main > res. Or you can simply put the highest resolution image in the root directory and I will use an online tool to make multiple sizes.

**Comment by elawhatson** [comment]
Everything ready😉

**Comment by LayoutXML** [comment]
Thanks, @elawhatson .
I will update the icon on the Google Play within a few days and will mention you in github, play store's app description, play store's changelog and in the settings (about screen).

If you are looking for a new project you would like to contribute you, I also have [TickTock Wear](https://github.com/LayoutXML/TickTock-Wear) project which I have not released yet (but will in a months time). [The icon I made for it is hideous](https://github.com/LayoutXML/TickTock-Wear/blob/master/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png). This application will play a ticking sound on the Android Wear OS smartwatches. So if you want to, you are free to contribute.

**Comment by elawhatson** [comment]
perfect! thanks mate! @LayoutXML .
of course, I would like to contribute to your other projects.
ill make a new issue on the Tick Tock-Wear in which you can tell me suggestions or ideas you have in mind for a logo that fits perfect to that project.👌

**Comment by LayoutXML** [comment]
Hi, I still haven't had time to update the logo when the app is downloaded but it has been set to 50% of people on the Google Play store (as an experiment). It seems that people prefer a real screenshot to a drawing (your icon is blue line in the graph) so I may leave the screenshot on the Google Play store but change it when the app is downloaded. Will run this experiment a bit longer.

![image](https://user-images.githubusercontent.com/34867100/48663643-fca72900-ea8a-11e8-8dd2-124dc8bfe7b2.png)
